db = db.getSiblingDB('ecommerce');

db.items.drop();
db.users.drop();
db.orders.drop();

db.items.insertMany([
	{
		title: 'Classic Cotton T-Shirt',
		price: 29.99,
		description: 'A comfortable and breathable classic cotton t-shirt, perfect for everyday wear.',
		category: 'Men',
		images: ['http://localhost:3001/data/default-1.webp', 'http://localhost:3001/data/hover-1.webp'],
		colors: ['Black', 'White', 'Navy'],
		sizes: ['S', 'M', 'L', 'XL'],
	},
	{
		title: 'Elegant Summer Dress',
		price: 49.99,
		description: 'Flowy and lightweight summer dress with floral patterns, perfect for sunny days.',
		category: 'Women',
		images: ['http://localhost:3001/data/default-2.webp', 'http://localhost:3001/data/hover-2.webp'],
		colors: ['Red', 'Yellow', 'Blue'],
		sizes: ['XS', 'S', 'M', 'L'],
	},
	{
		title: 'Kids Cozy Hoodie',
		price: 34.99,
		description: 'Soft and warm hoodie for kids, keeping them cozy during outdoor play.',
		category: 'Kids',
		images: ['http://localhost:3001/data/default-3.webp', 'http://localhost:3001/data/hover-3.webp'],
		colors: ['Grey', 'Pink', 'Green'],
		sizes: ['110', '120', '130', '140'],
	},
	{
		title: 'Slim Fit Denim Jeans',
		price: 59.99,
		description: 'Durable slim fit denim jeans with a modern stretch, designed for style and comfort.',
		category: 'Men',
		images: ['http://localhost:3001/data/default-4.webp', 'http://localhost:3001/data/hover-4.webp'],
		colors: ['Dark Blue', 'Light Blue', 'Black'],
		sizes: ['30', '32', '34', '36'],
	},
	{
		title: 'Casual Linen Blazer',
		price: 79.99,
		description: 'A lightweight linen blazer adding a touch of class to any casual outfit.',
		category: 'Women',
		images: ['http://localhost:3001/data/default-5.webp', 'http://localhost:3001/data/hover-5.webp'],
		colors: ['Beige', 'White'],
		sizes: ['S', 'M', 'L'],
	},
	{
		title: 'Kids Denim Jacket',
		price: 39.99,
		description: 'Stylish and sturdy denim jacket for kids, great for layering.',
		category: 'Kids',
		images: ['http://localhost:3001/data/default-6.webp', 'http://localhost:3001/data/hover-6.webp'],
		colors: ['Blue Denim'],
		sizes: ['120', '130', '140', '150'],
	},
	{
		title: 'Athletic Running Shorts',
		price: 24.99,
		description: 'Quick-dry athletic shorts with built-in liner, perfect for workouts.',
		category: 'Men',
		images: ['http://localhost:3001/data/default-7.webp', 'http://localhost:3001/data/hover-7.webp'],
		colors: ['Black', 'Charcoal'],
		sizes: ['M', 'L', 'XL'],
	},
	{
		title: 'Silk V-Neck Blouse',
		price: 45.99,
		description: 'Elegant silk blouse with a smooth touch, ideal for office or evening wear.',
		category: 'Women',
		images: ['http://localhost:3001/data/default-8.webp', 'http://localhost:3001/data/hover-8.webp'],
		colors: ['Ivory', 'Emerald', 'Burgundy'],
		sizes: ['S', 'M', 'L'],
	},
	{
		title: 'Kids Cotton Pajama Set',
		price: 19.99,
		description: "Fun and colorful cotton pajama set ensuring a good night's sleep.",
		category: 'Kids',
		images: ['http://localhost:3001/data/default-9.webp', 'http://localhost:3001/data/hover-9.webp'],
		colors: ['Stars Blue', 'Clouds Pink'],
		sizes: ['100', '110', '120', '130'],
	},
	{
		title: 'Waterproof Winter Coat',
		price: 119.99,
		description: 'Heavy-duty winter coat designed to withstand extreme cold and wet weather.',
		category: 'Men',
		images: ['http://localhost:3001/data/default-10.webp', 'http://localhost:3001/data/hover-10.webp'],
		colors: ['Olive', 'Black'],
		sizes: ['M', 'L', 'XL', 'XXL'],
	},
	{
		title: 'Activewear Sports Leggings',
		price: 39.99,
		description: 'High-waisted, moisture-wicking leggings designed for maximum flexibility.',
		category: 'Women',
		images: ['http://localhost:3001/data/default-11.webp', 'http://localhost:3001/data/hover-11.webp'],
		colors: ['Purple', 'Black'],
		sizes: ['XS', 'S', 'M', 'L'],
	},
	{
		title: 'Kids Woolen Beanie',
		price: 14.99,
		description: 'Warm woolen knit beanie with a cute pompom, keeping ears warm.',
		category: 'Kids',
		images: ['http://localhost:3001/data/default-12.webp', 'http://localhost:3001/data/hover-12.webp'],
		colors: ['Yellow', 'Grey'],
		sizes: ['One Size'],
	},
	{
		title: 'Leather Biker Jacket',
		price: 149.99,
		description: 'Premium leather biker jacket with silver zippers for a classic rock look.',
		category: 'Women',
		images: ['http://localhost:3001/data/default-13.webp', 'http://localhost:3001/data/hover-13.webp'],
		colors: ['Black', 'Brown'],
		sizes: ['S', 'M', 'L'],
	},
]);

db.users.insertMany([
	{
		_id: ObjectId('60d5ec38e86c0c2794c1a800'),
		username: 'admin',
		email: 'admin@example.com',
		password: '$2b$10$fqPI9ETCDl0FVNou4.XI.udzoXcJ5Jy8vG.KtNUuQ/nPSyu9FWagG',
		firstName: 'Admin',
		lastName: 'User',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		_id: ObjectId('60d5ec38e86c0c2794c1a801'),
		username: 'user',
		email: 'user@example.com',
		password: '$2b$10$fqPI9ETCDl0FVNou4.XI.udzoXcJ5Jy8vG.KtNUuQ/nPSyu9FWagG',
		firstName: 'Default',
		lastName: 'User',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
]);

db.orders.insertMany([
	{
		userID: ObjectId('60d5ec38e86c0c2794c1a801'),
		firstName: 'Default',
		lastName: 'User',
		address: '123 Main Street',
		city: 'New York',
		country: 'USA',
		products: [
			{
				title: 'Classic Cotton T-Shirt',
				price: 29.99,
				description: 'A comfortable and breathable classic cotton t-shirt, perfect for everyday wear.',
				category: 'Men',
				images: ['http://localhost:3001/data/default-1.webp', 'http://localhost:3001/data/hover-1.webp'],
				colors: ['Black', 'White', 'Navy'],
				sizes: ['S', 'M', 'L', 'XL'],
				selectedColor: 'Black',
				selectedSize: 'L',
			},
			{
				title: 'Elegant Summer Dress',
				price: 49.99,
				description: 'Flowy and lightweight summer dress with floral patterns, perfect for sunny days.',
				category: 'Women',
				images: ['http://localhost:3001/data/default-2.webp', 'http://localhost:3001/data/hover-2.webp'],
				colors: ['Red', 'Yellow', 'Blue'],
				sizes: ['XS', 'S', 'M', 'L'],
				selectedColor: 'Blue',
				selectedSize: 'S',
			},
		],
		total: 79.98,
		date: new Date().toISOString(),
	},
	{
		userID: ObjectId('60d5ec38e86c0c2794c1a800'),
		firstName: 'Admin',
		lastName: 'User',
		address: '456 Executive Blvd',
		city: 'San Francisco',
		country: 'USA',
		products: [
			{
				title: 'Leather Biker Jacket',
				price: 149.99,
				description: 'Premium leather biker jacket with silver zippers for a classic rock look.',
				category: 'Women',
				images: ['http://localhost:3001/data/default-13.webp', 'http://localhost:3001/data/hover-13.webp'],
				colors: ['Black', 'Brown'],
				sizes: ['S', 'M', 'L'],
				selectedColor: 'Black',
				selectedSize: 'M',
			},
		],
		total: 149.99,
		date: new Date().toISOString(),
	},
]);
